name: Lint code and compile setup script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

  compile:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [">=16.6.0 <17.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Compile test
        run: npm run compile && rm -rf dist
